### ISSUE TITLE
ValueError: "port" must be None or a string, not <class 'serial.tools.list_ports_linux.SysFS'>

### ISSUE THREAD

**Issue by ThinkTransit** [curiouswala/ampy-2#2]
Hi,

Great project!

Any ideas what I am doing wrong here?

Thanks.

```
(tangiblepy-2KOJwXct) patrick@TT-XPS:~/tangiblepy$ ./tpy setup
2021-07-04 19:53:51.854 | DEBUG    | __main__:main:40 - {'type': 'wifi', 'SSID': 'GIGI-BEAR', 'password': '****', 'device_pin': '1234', 'ip_address': '192.168.0.193', 'device_name': 'esp32'}
Device Types:
1: esp32
>> Select Device Type (1): 1
Serial_Ports:
1: /dev/ttyUSB0
>> Serial Port (1): 1
2021-07-04 19:53:55.047 | DEBUG    | plugins.esp32_plugin:device_firmware_download:36 - Downloading firmware for esp32
2021-07-04 19:53:55.048 | DEBUG    | plugins.esp32_plugin:device_firmware_download:38 - file exist
2021-07-04 19:53:55.048 | DEBUG    | plugins.esp32_plugin:device_firmware_download:46 - Firmware at downloads/esp32-idf3-20200902-v1.13.bin
2021-07-04 19:53:55.048 | DEBUG    | plugins.esp32_plugin:device_firmware_install:52 - {'download_path': 'downloads', 'db_filename': 'db.json', 'wifi': {'db_filename': 'db.json', 'datatype': 'wifi'}, 'device': 'esp32', 'serial_port': <serial.tools.list_ports_linux.SysFS object at 0x7ff53ea1cf70>, 'mpy_installed': False, 'firmware_path': 'downloads/esp32-idf3-20200902-v1.13.bin'}
>> Install Firmware y/n (y): n
ampy2_connection_setup calling...
2021-07-04 19:54:02.274 | DEBUG    | plugins.pico_plugin:device_connection_setup:20 - ampy2_connection_setup calling...
2021-07-04 19:54:02.274 | DEBUG    | plugins.esp32_plugin:device_connection_setup:72 - esp32_connection_setup calling...
2021-07-04 19:54:02.275 | DEBUG    | plugins.esp32_plugin:device_connection_setup:73 - {'download_path': 'downloads', 'db_filename': 'db.json', 'wifi': {'db_filename': 'db.json', 'datatype': 'wifi'}, 'device': 'esp32', 'serial_port': <serial.tools.list_ports_linux.SysFS object at 0x7ff53ea1cf70>, 'mpy_installed': True, 'firmware_path': 'downloads/esp32-idf3-20200902-v1.13.bin'}
2021-07-04 19:54:02.276 | DEBUG    | plugins.esp32_plugin:device_connection_setup:78 - 2
{'type': 'wifi', 'SSID': 'GIGI-BEAR', 'password': '****', 'device_pin': '1234', 'ip_address': '192.168.0.193', 'device_name': 'esp32'}
>> Use Above WiFi Settings  y/n (y):  y
2021-07-04 19:54:05.851 | DEBUG    | plugins.esp32_plugin:device_connection_setup:85 - Using old wifi configration.
Setting up WiFi...
2021-07-04 19:54:05.851 | DEBUG    | plugins.esp32_plugin:device_connection_setup:106 - {'download_path': 'downloads', 'db_filename': 'db.json', 'wifi': {'db_filename': 'db.json', 'datatype': 'wifi'}, 'device': 'esp32', 'serial_port': <serial.tools.list_ports_linux.SysFS object at 0x7ff53ea1cf70>, 'mpy_installed': True, 'firmware_path': 'downloads/esp32-idf3-20200902-v1.13.bin'}
2021-07-04 19:54:05.852 | DEBUG    | plugins.esp32_plugin:device_connection_setup:113 - /home/patrick/tangiblepy/espfiles
Traceback (most recent call last):
  File "/home/patrick/tangiblepy/./tpy", line 113, in <module>
    main()
  File "/home/patrick/tangiblepy/./tpy", line 48, in main
    device_setup(config)
  File "/home/patrick/tangiblepy/./tpy", line 23, in device_setup
    config.pm.hook.ampy2_connection_setup(config=config)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/patrick/tangiblepy/core_plugins/core.py", line 18, in ampy2_connection_setup
    config.pm.hook.device_connection_setup(config=config)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/patrick/tangiblepy/plugins/esp32_plugin.py", line 130, in device_connection_setup
    ser.port = port
  File "/home/patrick/.local/share/virtualenvs/tangiblepy-2KOJwXct/lib/python3.9/site-packages/serial/serialutil.py", line 268, in port
    raise ValueError('"port" must be None or a string, not {}'.format(type(port)))
ValueError: "port" must be None or a string, not <class 'serial.tools.list_ports_linux.SysFS'>
```

**Comment by curiouswala** [comment]
instead of 1, you can just press enter and it'll by default select 1.  We probably missed handling integer input in one of the options. We will fix this behaviour by tomorrow. Thank you very much for raising the issue.

**Comment by curiouswala** [comment]
It should be fixed now. please let me know if you face any other issues.
